keywords:

  - glsl
  - hlsl
  # - shader
  # - shaders

exclude:
  users:
    - awwwards
    - margheritapvr
    - git_shit
    - scenomics
    - cesar3dartist
    - cem_yuksel
    - shade_radio
    - nerddisco
    - agoblinlife
    - pablolarah
    - helpwantedbot
    #- jogoinka
  words:
    - jangoinka.com
    - udemy
    - instagram
    - awwwards


settings:

  language: en
  max_tweet: 4
  max_hashtags: 8

